# Generated by Django 3.0 on 2020-02-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerText',
            fields=[
                ('C_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('Describe', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'CustomerAsking',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=252, unique=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='IndexImage',
            fields=[
                ('img_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='img.jpg', upload_to='')),
            ],
            options={
                'db_table': 'IndexImg',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirmPassword', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'other')])),
            ],
        ),
    ]
