# Generated by Django 3.0 on 2020-02-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexImage',
        ),
    ]
