# Generated by Django 3.0 on 2020-02-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_delete_indeximage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to=''),
        ),
    ]
