# Generated by Django 3.0 on 2020-02-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_auto_20200215_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to=''),
        ),
    ]
