# Generated by Django 3.0 on 2020-02-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0006_auto_20200215_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
